global using System;
global using System.Collections.Generic;
global using System.Threading.Tasks;
global using System.Linq;

// Domain namespaces
global using InLeague.Domain.Features.Leagues;
global using InLeague.Domain.Features.Drivers;
global using InLeague.Domain.Features.Karts;
global using InLeague.Domain.Features.Races;
global using InLeague.Domain.Features.Races.Enums;
global using InLeague.Domain.Features.Users;

// Application namespaces
global using InLeague.Application.Common.Interfaces;
global using InLeague.Application.Features.Auth.DTOs;
global using InLeague.Application.Features.Auth.Services;
global using InLeague.Application.Features.Auth.Interfaces;
global using InLeague.Application.Features.Drivers.DTOs;
global using InLeague.Application.Features.Drivers.Services;
global using InLeague.Application.Features.Drivers.Interfaces;
global using InLeague.Application.Features.Karts.DTOs;
global using InLeague.Application.Features.Karts.Services;
global using InLeague.Application.Features.Karts.Interfaces;
global using InLeague.Application.Features.Leagues.DTOs;
global using InLeague.Application.Features.Leagues.Services;
global using InLeague.Application.Features.Leagues.Interfaces;
global using InLeague.Application.Features.Races.DTOs;
global using InLeague.Application.Features.Races.Services;
global using InLeague.Application.Features.Races.Interfaces;
global using InLeague.Application.Features.RaceResults.DTOs;
global using InLeague.Application.Features.RaceResults.Services;
global using InLeague.Application.Features.RaceResults.Interfaces;
global using InLeague.Application.Features.Auth.Validators;
global using InLeague.Application.Features.Drivers.Validators;
global using InLeague.Application.Features.Karts.Validators;
global using InLeague.Application.Features.Leagues.Validators;
global using InLeague.Application.Features.Races.Validators;
global using InLeague.Application.Features.RaceResults.Validators;
