// <auto-generated />
using System;
using InLeague.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InLeague.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260609192122_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InLeague.Domain.Features.Drivers.Driver", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("RacingNumber")
                        .HasColumnType("text")
                        .HasColumnName("racing_number");

                    b.HasKey("Id")
                        .HasName("pk_drivers");

                    b.ToTable("drivers", (string)null);
                });

            modelBuilder.Entity("InLeague.Domain.Features.Karts.Kart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Model")
                        .HasColumnType("text")
                        .HasColumnName("model");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("number");

                    b.HasKey("Id")
                        .HasName("pk_karts");

                    b.HasIndex("Number")
                        .IsUnique()
                        .HasDatabaseName("ix_karts_number");

                    b.ToTable("karts", (string)null);
                });

            modelBuilder.Entity("InLeague.Domain.Features.Leagues.League", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.HasKey("Id")
                        .HasName("pk_leagues");

                    b.ToTable("leagues", (string)null);
                });

            modelBuilder.Entity("InLeague.Domain.Features.Leagues.LeagueAdmin", b =>
                {
                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uuid")
                        .HasColumnName("league_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LeagueId", "UserId")
                        .HasName("pk_league_admins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_league_admins_user_id");

                    b.ToTable("league_admins", (string)null);
                });

            modelBuilder.Entity("InLeague.Domain.Features.Races.Race", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uuid")
                        .HasColumnName("league_id");

                    b.Property<string>("Location")
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("NumberOfLaps")
                        .HasColumnType("integer")
                        .HasColumnName("number_of_laps");

                    b.Property<DateTime>("RaceDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("race_date");

                    b.HasKey("Id")
                        .HasName("pk_races");

                    b.HasIndex("LeagueId")
                        .HasDatabaseName("ix_races_league_id");

                    b.ToTable("races", (string)null);
                });

            modelBuilder.Entity("InLeague.Domain.Features.Races.RaceResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uuid")
                        .HasColumnName("driver_id");

                    b.Property<int?>("FinishingPosition")
                        .HasColumnType("integer")
                        .HasColumnName("finishing_position");

                    b.Property<Guid>("KartId")
                        .HasColumnType("uuid")
                        .HasColumnName("kart_id");

                    b.Property<long>("LapTimeMs")
                        .HasColumnType("bigint")
                        .HasColumnName("lap_time_ms");

                    b.Property<int>("LapsCompleted")
                        .HasColumnType("integer")
                        .HasColumnName("laps_completed");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<Guid>("RaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("race_id");

                    b.Property<int>("StartingPosition")
                        .HasColumnType("integer")
                        .HasColumnName("starting_position");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<long>("TotalTimeMs")
                        .HasColumnType("bigint")
                        .HasColumnName("total_time_ms");

                    b.HasKey("Id")
                        .HasName("pk_race_results");

                    b.HasIndex("DriverId")
                        .HasDatabaseName("ix_race_results_driver_id");

                    b.HasIndex("KartId")
                        .HasDatabaseName("ix_race_results_kart_id");

                    b.HasIndex("RaceId", "DriverId")
                        .IsUnique()
                        .HasDatabaseName("ix_race_results_race_id_driver_id");

                    b.ToTable("race_results", (string)null);
                });

            modelBuilder.Entity("InLeague.Domain.Features.Users.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Admin"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Name = "User"
                        });
                });

            modelBuilder.Entity("InLeague.Domain.Features.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("DriverId")
                        .HasColumnType("uuid")
                        .HasColumnName("driver_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("LastName")
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("DriverId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_driver_id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("InLeague.Domain.Features.Users.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_roles_role_id");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("InLeague.Domain.Features.Leagues.LeagueAdmin", b =>
                {
                    b.HasOne("InLeague.Domain.Features.Leagues.League", "League")
                        .WithMany("LeagueAdmins")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_league_admins_leagues_league_id");

                    b.HasOne("InLeague.Domain.Features.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_league_admins_users_user_id");

                    b.Navigation("League");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InLeague.Domain.Features.Races.Race", b =>
                {
                    b.HasOne("InLeague.Domain.Features.Leagues.League", "League")
                        .WithMany("Races")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_races_leagues_league_id");

                    b.Navigation("League");
                });

            modelBuilder.Entity("InLeague.Domain.Features.Races.RaceResult", b =>
                {
                    b.HasOne("InLeague.Domain.Features.Drivers.Driver", "Driver")
                        .WithMany("Results")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_race_results_drivers_driver_id");

                    b.HasOne("InLeague.Domain.Features.Karts.Kart", "Kart")
                        .WithMany("Results")
                        .HasForeignKey("KartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_race_results_karts_kart_id");

                    b.HasOne("InLeague.Domain.Features.Races.Race", "Race")
                        .WithMany("Results")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_race_results_races_race_id");

                    b.Navigation("Driver");

                    b.Navigation("Kart");

                    b.Navigation("Race");
                });

            modelBuilder.Entity("InLeague.Domain.Features.Users.User", b =>
                {
                    b.HasOne("InLeague.Domain.Features.Drivers.Driver", "Driver")
                        .WithOne("User")
                        .HasForeignKey("InLeague.Domain.Features.Users.User", "DriverId")
                        .HasConstraintName("fk_users_drivers_driver_id");

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("InLeague.Domain.Features.Users.UserRole", b =>
                {
                    b.HasOne("InLeague.Domain.Features.Users.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_roles_role_id");

                    b.HasOne("InLeague.Domain.Features.Users.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_users_user_id");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InLeague.Domain.Features.Drivers.Driver", b =>
                {
                    b.Navigation("Results");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InLeague.Domain.Features.Karts.Kart", b =>
                {
                    b.Navigation("Results");
                });

            modelBuilder.Entity("InLeague.Domain.Features.Leagues.League", b =>
                {
                    b.Navigation("LeagueAdmins");

                    b.Navigation("Races");
                });

            modelBuilder.Entity("InLeague.Domain.Features.Races.Race", b =>
                {
                    b.Navigation("Results");
                });

            modelBuilder.Entity("InLeague.Domain.Features.Users.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("InLeague.Domain.Features.Users.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
